# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestdeleteProduct():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testdeleteProduct(self):
    self.driver.get("https://localhost:7010/")
    self.driver.set_window_size(1382, 784)
    self.driver.find_element(By.LINK_TEXT, "Product").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    assert self.driver.switch_to.alert.text == "Are you sure?"
    self.driver.switch_to.alert.accept()
  
