# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesteditProduct():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testeditProduct(self):
    self.driver.get("https://localhost:7010/")
    self.driver.set_window_size(1382, 784)
    self.driver.find_element(By.LINK_TEXT, "Product").click()
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    self.driver.find_element(By.ID, "Description").click()
    self.driver.find_element(By.ID, "Description").send_keys("Caneta tablet Apple escrita fina e detalhada")
    self.driver.find_element(By.ID, "Brand").click()
    self.driver.find_element(By.ID, "Brand").send_keys("Apple PC")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
