# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestaddProduct():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testaddProduct(self):
    self.driver.get("https://localhost:7010/")
    self.driver.set_window_size(2062, 838)
    self.driver.find_element(By.LINK_TEXT, "Product").click()
    self.driver.find_element(By.LINK_TEXT, "New Product").click()
    self.driver.find_element(By.ID, "Name").click()
    self.driver.find_element(By.ID, "Name").send_keys("Apple Pencil")
    self.driver.find_element(By.ID, "Brand").send_keys("Apple")
    dropdown = self.driver.find_element(By.ID, "Category")
    dropdown.find_element(By.XPATH, "//option[. = 'Phones']").click()
    dropdown = self.driver.find_element(By.ID, "Category")
    dropdown.find_element(By.XPATH, "//option[. = 'Computers']").click()
    dropdown = self.driver.find_element(By.ID, "Category")
    dropdown.find_element(By.XPATH, "//option[. = 'Accessories']").click()
    self.driver.find_element(By.ID, "Price").send_keys("500")
    self.driver.find_element(By.ID, "Description").send_keys("Caneta tablet")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
